name: "Report Website"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Delete previous result
      run: rm -f docs/details* docs/overview* 
    - name: Build Report with Maven
      run: mvn clean install -Pgenerate-site --file runners/pom.xml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Report Website Published